"""cascading deletion?

Revision ID: 922a800c3370
Revises: a4d28dae9f60
Create Date: 2023-11-25 06:22:29.038756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922a800c3370'
down_revision = 'a4d28dae9f60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_interactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
