"""Added image, boolean, swapped order of Car

Revision ID: a4d28dae9f60
Revises: 60696c16c30e
Create Date: 2023-11-24 21:10:41.591352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d28dae9f60'
down_revision = '60696c16c30e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('car_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mileage', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('mileage')
        batch_op.drop_column('car_name')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
